




//this trigger is installed from adminhelp email address
function sendRequestEmail(e) {



  let ss = e.source;
  let sheet = ss.getActiveSheet();

  let range = e.range;
  let row = range.getRow();
  let column = range.getColumn();

  let value = e.value;




  let sendEmailCol = sheet.getRange("SEND_REQUEST_EMAIL").getColumn()

  if (column == sendEmailCol && row > 0 && (value == true || value == "TRUE")) {

    let forwardTo = sheet.getRange(row, 7).getValue()
    if (forwardTo != "" && forwardTo != null) {
      let emailsSheet = ss.getSheetByName("Emails List");
      let emailsList = emailsSheet.getRange(2, 1, emailsSheet.getLastRow() - 1, 2).getValues();
      let names = emailsList.map(r => r[0]);

      let forwardToIndex = names.indexOf(forwardTo);
      let emails = emailsList[forwardToIndex][1];

      if (emails != "" && emails != null) {

        try {

          let rowData = sheet.getRange(row, 1, 1, 11).getDisplayValues()[0];
          let link = rowData[5]
          let subject = "New Staff Request";
          let body = "Hello,\n\nPlease see the following mail addressed to either you or your team. If this mail is not for you, please reply to this email.\n\nSummary/Subject: " + rowData[5] + "\nRequest: " + rowData[6] + "\n\nThis email is autogenerated.";

          body = "This email is autogenerated."


          GmailApp.sendEmail(emails.replace(/\s/g, ""), subject, body, {
            bcc: "admin@ssdspc.com"
          })




          //GmailApp.sendEmail("rashid_khan143@yahoo.com", subject, body)

          sheet.getRange(row, sendEmailCol + 1).setValue(Utilities.formatDate(new Date(), Session.getScriptTimeZone(), "MM/dd/yyyy HH:MM"))


        } catch (err) { sheet.getRange(row, sendEmailCol + 1).setValue(err) }
      }
    }



  }


}



















