


const WEBAPP_URL = "https://script.google.com/a/macros/ssdspc.com/s/AKfycbwpAlztj8FAOzyuVY0U1aBbwImbgGwmRv-NXYxpv16JU7vhyVzG_y68JlpBoWoXCwO4gg/exec"

//this trigger is installed from adminhelp email address
function onEditInstall(e) {

  onEditSortMicro(e)

  let ss = e.source;
  let sheet = ss.getActiveSheet();

  let range = e.range;
  let row = range.getRow();
  let column = range.getColumn();

  let value = e.value;


  if (sheet.getSheetId() == 839054197) {

    if (column == 7 && row > 2 && value != "") {

      let fileUrl = sheet.getRange(row, column - 1).getValue();
      const folderIdMatch = fileUrl.match(/[-\w]{25,}/);
      let file = DriveApp.getFileById(folderIdMatch);
      file.setName(value)
      sheet.getRange(row, column - 2).setValue(value);

    }

  } else if (sheet.getSheetId() == 0) {

    let sendEmailCol = sheet.getRange("NEEDS_REVIEW_EMAIL").getColumn()

    if (column == sendEmailCol && row > 0 && (value == true || value == "TRUE")) {

      let forwardTo = sheet.getRange(row, 14).getValue()
      if (forwardTo != "" && forwardTo != null) {
        let emailsSheet = ss.getSheetByName("Emails List");
        let emailsList = emailsSheet.getRange(2, 1, emailsSheet.getLastRow() - 1, 2).getValues();
        let names = emailsList.map(r => r[0]);

        let forwardToIndex = names.indexOf(forwardTo);
        let emails = emailsList[forwardToIndex][1];

        if (emails != "" && emails != null) {

          try {

            let rowData = sheet.getRange(row, 1, 1, 13).getDisplayValues()[0];
            let link = rowData[7]
            let subject = "Document Needing Review";
            let body = "Hello,\n\nPlease see the following mail addressed to either you or your team. If this mail is not for you, please reply to this email.\n\nAdmin Notes: " + rowData[12] + "\n\n" + link + "\n\nThis email is autogenerated.";


            GmailApp.sendEmail(emails.replace(/\s/g, ""), subject, body, {
              bcc: "admin@ssdspc.com"
            })




            //GmailApp.sendEmail("rashid_khan143@yahoo.com", subject, body)

            sheet.getRange(row, sendEmailCol + 1).setValue(Utilities.formatDate(new Date(), Session.getScriptTimeZone(), "MM/dd/yyyy HH:MM"))


          } catch (err) { sheet.getRange(row, sendEmailCol + 1).setValue(err) }
        }
      }



    }

  }
}




























